# Generated by Django 4.0.1 on 2022-01-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
